# Generated by Django 2.2.5 on 2019-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nome',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(default=0, help_text='Nome fantasia da empresa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(default=1, help_text='Razão Social da empresa', max_length=100),
            preserve_default=False,
        ),
    ]
