# Generated by Django 2.2.5 on 2019-09-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_auto_20190914_1203'),
        ('horas_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.Colaborador'),
            preserve_default=False,
        ),
    ]
