# Generated by Django 2.2.5 on 2019-09-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_auto_20190914_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
