# Generated by Django 2.2.5 on 2019-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_auto_20190930_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
